framework:
    assets:
        packages:
            # Provide asset manaifest for the bundle.
            materialtheme:
                json_manifest_path: '%kernel.project_dir%/public/bundles/materialtheme/manifest.json'
                base_path: bundles/materialtheme
